名称：1获取最新剧本
在：
  时间表：
    -定时任务：' 5 */3 * * * '
  工作流调度：
  观看：
    类型：开始
  存储库调度：
    类型：sync-zero205-scripts
工作：
  回购同步：
    环境：
      PAT : ${{secrets.PAT }} #这里PAT需要申请，教程见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key : ${{ secrets.GITEE_PRIVATE_KEY } #我自己同步到gitee使用，其他人可忽忽
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    步骤：
      -用途：动作/结帐@v2
        与：
          持久凭证：假

      -名称：同步 zero205-scripts
        用途：repo-sync/github-sync@v2
        如果：env.PAT
        与：
          source_repo : " https://github.com//lukesyy/jd_yun.git "
          源分支：“主要”
          目的地分支：“主要”
          github_token : ${{ secrets.PAT }}
